version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
     MYSQL_ROOT_USERNAME: root
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: family-board
     MYSQL_USER:     root
     MYSQL_PASSWORD: root
     TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports:
      - 9000:9000
    depends_on:
      - db
  proxy:
    build: ./docker/nginx
    ports:
      - 8000:80
    depends_on:
      - web
